version: '3.8'

services:
  api:
    build:
      context: ./api  # Build the API service from the api folder
    ports:
      - "6000:6000"   # Expose port 6000 on the host
    networks:
      - my_network

  etl:
    build:
      context: ./etl  # Build the ETL service from the etl folder
    depends_on:
      - api  # Make sure the ETL service waits for the API service to be up
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
